# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arthur/Desktop/PG-Raytracing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arthur/Desktop/PG-Raytracing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/Desktop/PG-Raytracing/CMakeFiles /home/arthur/Desktop/PG-Raytracing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/Desktop/PG-Raytracing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pg

# Build rule for target.
pg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pg
.PHONY : pg

# fast build rule for target.
pg/fast:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/build
.PHONY : pg/fast

project/BSurfaces.o: project/BSurfaces.cpp.o

.PHONY : project/BSurfaces.o

# target to build an object file
project/BSurfaces.cpp.o:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/BSurfaces.cpp.o
.PHONY : project/BSurfaces.cpp.o

project/BSurfaces.i: project/BSurfaces.cpp.i

.PHONY : project/BSurfaces.i

# target to preprocess a source file
project/BSurfaces.cpp.i:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/BSurfaces.cpp.i
.PHONY : project/BSurfaces.cpp.i

project/BSurfaces.s: project/BSurfaces.cpp.s

.PHONY : project/BSurfaces.s

# target to generate assembly for a file
project/BSurfaces.cpp.s:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/BSurfaces.cpp.s
.PHONY : project/BSurfaces.cpp.s

project/RayTracing.o: project/RayTracing.cpp.o

.PHONY : project/RayTracing.o

# target to build an object file
project/RayTracing.cpp.o:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/RayTracing.cpp.o
.PHONY : project/RayTracing.cpp.o

project/RayTracing.i: project/RayTracing.cpp.i

.PHONY : project/RayTracing.i

# target to preprocess a source file
project/RayTracing.cpp.i:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/RayTracing.cpp.i
.PHONY : project/RayTracing.cpp.i

project/RayTracing.s: project/RayTracing.cpp.s

.PHONY : project/RayTracing.s

# target to generate assembly for a file
project/RayTracing.cpp.s:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/RayTracing.cpp.s
.PHONY : project/RayTracing.cpp.s

project/camera.o: project/camera.cpp.o

.PHONY : project/camera.o

# target to build an object file
project/camera.cpp.o:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/camera.cpp.o
.PHONY : project/camera.cpp.o

project/camera.i: project/camera.cpp.i

.PHONY : project/camera.i

# target to preprocess a source file
project/camera.cpp.i:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/camera.cpp.i
.PHONY : project/camera.cpp.i

project/camera.s: project/camera.cpp.s

.PHONY : project/camera.s

# target to generate assembly for a file
project/camera.cpp.s:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/camera.cpp.s
.PHONY : project/camera.cpp.s

project/geom.o: project/geom.cpp.o

.PHONY : project/geom.o

# target to build an object file
project/geom.cpp.o:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/geom.cpp.o
.PHONY : project/geom.cpp.o

project/geom.i: project/geom.cpp.i

.PHONY : project/geom.i

# target to preprocess a source file
project/geom.cpp.i:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/geom.cpp.i
.PHONY : project/geom.cpp.i

project/geom.s: project/geom.cpp.s

.PHONY : project/geom.s

# target to generate assembly for a file
project/geom.cpp.s:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/geom.cpp.s
.PHONY : project/geom.cpp.s

project/lights.o: project/lights.cpp.o

.PHONY : project/lights.o

# target to build an object file
project/lights.cpp.o:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/lights.cpp.o
.PHONY : project/lights.cpp.o

project/lights.i: project/lights.cpp.i

.PHONY : project/lights.i

# target to preprocess a source file
project/lights.cpp.i:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/lights.cpp.i
.PHONY : project/lights.cpp.i

project/lights.s: project/lights.cpp.s

.PHONY : project/lights.s

# target to generate assembly for a file
project/lights.cpp.s:
	$(MAKE) -f CMakeFiles/pg.dir/build.make CMakeFiles/pg.dir/project/lights.cpp.s
.PHONY : project/lights.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pg"
	@echo "... project/BSurfaces.o"
	@echo "... project/BSurfaces.i"
	@echo "... project/BSurfaces.s"
	@echo "... project/RayTracing.o"
	@echo "... project/RayTracing.i"
	@echo "... project/RayTracing.s"
	@echo "... project/camera.o"
	@echo "... project/camera.i"
	@echo "... project/camera.s"
	@echo "... project/geom.o"
	@echo "... project/geom.i"
	@echo "... project/geom.s"
	@echo "... project/lights.o"
	@echo "... project/lights.i"
	@echo "... project/lights.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

